### ISSUE TITLE
Downloading CSS file returns true.html

### ISSUE THREAD

**Issue by KaKi87** [subnub/myDrive#42]
Hello, downloading the CSS file under myDrive/Folder returns a true.html file, is that normal ? Thanks

**Comment by subnub** [comment]
Hey. I am having a hard time reproducing this issue. When I download a CSS file it seems to download normally, I wouldn’t think the file type should effect the download. Is it only CSS files that cause this issue? Like if you try to download a non-CSS file will it work? Or will it show the same issue?

**Comment by subnub** [comment]
Okay that makes more sense! Definitely some type of error going on, i'm guessing something to do with configuring the app with setup. Are you getting any type of error in your terminal? If not, it is most likely some type of client issue. Please check in the terminal for any errors, and also please check in the chrome developer tools. You can get to this by pressing the 3 veridical dots on the top right of Chrome, going to `More tools`, and selecting `Developer Tools`. Make sure you are on the tab that says `console`. Then just attempt to download any file, and see if there is an error in the console. After all of this, let me know what error you are seeing, because that will make it all much easier.

**Comment by KaKi87** [comment]
As I said, I was testing [the demo](https://mydrive-3.herokuapp.com/home).
I did opened devtools, and only found `main updated` and `download file` logs, but no error.
Also I'm a webdev. ;)

**Comment by subnub** [comment]
Oh! I missed that part. The demo does NOT allow you to download, upload, edit the name, delete, or anything of the sort. Since I do not want users uploading random things, and changing names and such to things that could be non-friendly. Plus it would cost money whenever someone tries to download something.

It actually does say this in the demo tab of the readme, `The Upload and Download Features, and other core features, are disabled in the demo.`

But yeah, thats intended. Hopefully this clears up any questions, let me know. :)

**Comment by KaKi87** [comment]
Yes, removing the popup would be a solution to your immediate issue.
However, yours is the first cloud software demo I've ever seen which blocks downloads.
Not being able to upload is common.
But, not being able to download ?
That's very weird.

**Comment by subnub** [comment]
I am just using the free tier of Heroku, I could maybe allow users to download, but then there would be a fairly high chance of the dynamo being shut down since its using to much traffic (plus the info is also stored in Atlas, which isn't good for large files). The dynamo usually already gets to 80% of its traffic before the end of the month, so it would most likely push it over the limit.

When I first made this I didn't have much money, so It wasn't really an option to provide downloads since I do not make any money off of this. I do have a software engineering job now though. So maybe I will reconsider this. That being said, I would need to have some way to stop users for spamming downloads and trying to drive up the bill.

I am actually curious, could you link me some of these demos that does not block downloads? Like one that has file sizes similar to what myDrive has. Because I would like to see how they handle all of this.

**Comment by subnub** [comment]
Closing due to no response, feel free to reopen if needed.

**Comment by KaKi87** [comment]
| Service                                                                                     | Username                | Password                                   | Features                                |
| ------------------------------------------------------------------------------------------- | ----------------------- | ------------------------------------------ | --------------------------------------- |
| [NextCloud](https://try.nextcloud.com/)                                                     | *auto-generated*        | `demo`                                     | Preview, download, upload               |
| [ownCloud](https://demo.owncloud.org/login)                                                 | `demo`                  | *same*                                     | Preview, download, upload               |
| [Seafile](https://demo.seafile.top/accounts/login/?next=/)                                  | `abc@abc.com`           | `abc`                                      | Preview, download, upload               |
| [Pydio](https://demo.pydio.com/login)                                                       | `alice`, `bob`, `admin` | *same*                                     | Preview, download, upload               |
| [MinIO](https://play.minio.io:9000/minio/login)                                             | `Q3AM3UQ867SPQQA43P2F`  | `zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG` | Download, upload *(no preview feature)* |
| [Filestash](https://demo.filestash.app/login?type=webdav&url=https://webdav.filestash.app/) | *auto-login*            |                                            | Preview, download *(upload forbidden)*  |
| [Tracim](https://demo.tracim.fr/ui/login)                                                   | `admin@admin.admin`     | *same*                                     | Preview, download, upload               |
