### ISSUE TITLE
unable to login exept from localhost

### ISSUE THREAD

**Issue by Quentin811** [subnub/myDrive#6]
Hey i installed your app this morning and i able to login and register account from localhost but not from another client inside the same network, so how do i login from another computer ?

**Comment by jenthered** [comment]
I reopened the file please retry

**Comment by subnub** [comment]
By default when you run the "npm run init" script, it will ask you what URL you want to use, if you leave it blank it will use localhost. But you can type in your computers IP address in order to allow others to connect on the same network. Then they would type in your computers IP address to access myDrive. 
Please note running npm run init will destroy the password inside of the /config/prod.env file, so make sure to backup this file, and password. And then enter that password when you rerun npm run init, or you will not be able to login to already created accounts.

Also you will not be able to access myDrive outside of the network, unless you use port forwarding.

**Comment by Quentin811** [comment]
Ok thanks you for answer .  I will test this morning .

**Comment by Quentin811** [comment]
everything works normally it's great, thank you very much
